### ISSUE TITLE
Solution wrong: small typo in function leading to incorrect results

### ISSUE THREAD

**Issue by meppes** [learn-co-curriculum/dsc-intervals-with-t-distribution-lab#1]
Hello,

In the solution, the 'conf_interval' function has the sample standard deviation incorrectly set to a global variable set earlier in the lesson (sample_stdev), rather than a new local calculation specific to the sample argument. This creates a scenario where all margin of errors are the same when we go to loop through the 25 iterations. 

Within the conf_interval function:
'sigma = sample_stdev/math.sqrt(sample_size) ' 

should be:

'sigma = sample.std()/math.sqrt(sample_size)'

**Comment by mas16** [comment]
Hi meppes, thanks for pointing this out! It has been corrected.
