### ISSUE TITLE
Function hard codes to wrong variable

### ISSUE THREAD

**Issue by Co-nn** [learn-co-curriculum/dsc-intervals-with-t-distribution-lab#3]
Confidence Intervals of Repeated Samples in the solutions branch:

You have, 
    # Sample size
    n = len(sample)
    # Sample mean
    x_hat = sample.mean()
    
    # Standard error of the mean
    standard_error = sample.std(ddof=1)/math.sqrt(sample_size)

However sample size is defined in the function as n not sample_size. So it should look like,
    # Sample size
    n = len(sample)
    # Sample mean
    x_hat = sample.mean()
    
    # Standard error of the mean
    standard_error = sample.std(ddof=1)/math.sqrt(n)

**Comment by ismayc** [comment]
Thanks for flagging. This was fixed in https://github.com/learn-co-curriculum/dsc-intervals-with-t-distribution-lab/commit/32685262c9a9c083b53c7d2ee806bed144832cb1
